var searchData=
[
  ['data_0',['Data',['../_persistent_data.html',1,'Persistent Data'],['../_player_data.html',1,'Player Data'],['../_player_data.html#RetrievingPlayerData',1,'Retrieving Player Data'],['../_player_data.html#SavingPlayerData',1,'Saving Player Data']]],
  ['datamanager_1',['DataManager',['../class_multimorphic_1_1_p3_app_1_1_data_1_1_data_manager.html',1,'Multimorphic::P3App::Data']]],
  ['datamanagermode_2',['DataManagerMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_data_manager_mode.html',1,'Multimorphic::P3App::Modes::Data']]],
  ['dataobject_3',['dataObject',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_item.html#a534d8241591c8952d63b5a32b9012ca0',1,'Multimorphic.P3App.GUI.MenuItem.dataObject'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_selector_item.html#a68cc5caa2af415ba64c10b93c586b737',1,'Multimorphic.P3App.GUI.Selector.SelectorItem.dataObject']]],
  ['dataobjectsareprepared_4',['dataObjectsArePrepared',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_base.html#ad957d0795ad1ebc6b372a54373d433ba',1,'Multimorphic.P3App.GUI.MenuBase.dataObjectsArePrepared'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_selector.html#a0281261858850d22ff81d8219f440d91',1,'Multimorphic.P3App.GUI.Selector.Selector.dataObjectsArePrepared']]],
  ['datastoragecontroller_5',['DataStorageController',['../class_multimorphic_1_1_p3_app_1_1_data_1_1_data_storage_controller.html',1,'Multimorphic::P3App::Data']]],
  ['datastoragemanager_6',['DataStorageManager',['../class_multimorphic_1_1_p3_app_1_1_data_1_1_data_storage_manager.html',1,'Multimorphic::P3App::Data']]],
  ['dataversion_7',['DataVersion',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_data_manager_mode.html#a906d16c2ed5ff1668b85ee27fca4edf8',1,'Multimorphic::P3App::Modes::Data::DataManagerMode']]],
  ['dbmanager_8',['DBManager',['../class_multimorphic_1_1_p3_app_1_1_data_1_1_d_b_manager.html',1,'Multimorphic::P3App::Data']]],
  ['dbversion_9',['DBVersion',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_data_manager_mode.html#a5a756f3905a4bd77467bd271e572f28c',1,'Multimorphic::P3App::Modes::Data::DataManagerMode']]],
  ['debug_20gameattributes_10',['Debug GameAttributes',['../_persistent_data.html#DebugAttributes',1,'']]],
  ['debugdisplay_11',['DebugDisplay',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_debug_display.html',1,'Multimorphic::P3App::GUI']]],
  ['debugging_20events_12',['Debugging Events',['../_mode_layer.html#DebuggingEvents',1,'']]],
  ['decimalplaces_13',['decimalPlaces',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_category.html#a7cdd82be251274597ddad3c19d6ff451',1,'Multimorphic::P3App::Modes::Data::HighScoreCategory']]],
  ['default_20flipper_20strength_14',['Setting Default Flipper Strength',['../_physical_features.html#SettingDefaultFlipperStrength',1,'']]],
  ['default_20gameattributes_15',['Default GameAttributes',['../_persistent_data.html#CustomizingDefaultGameAttributes',1,'Customizing Default GameAttributes'],['../_persistent_data.html#DefaultGameAttributes',1,'Default GameAttributes']]],
  ['defaultmixergroup_16',['defaultMixerGroup',['../class_multimorphic_1_1_p3_s_a_1_1_g_u_i_1_1_p3_s_a_audio.html#a268acfe261fdfbd40654d36212748877',1,'Multimorphic::P3SA::GUI::P3SAAudio']]],
  ['defaultnames_17',['defaultNames',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_category.html#a38ac6e65710c519a29e2d32b74974840',1,'Multimorphic::P3App::Modes::Data::HighScoreCategory']]],
  ['defaultvalues_18',['defaultValues',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_category.html#ac14120b077437d94d5fa1b672a7cc7c6',1,'Multimorphic::P3App::Modes::Data::HighScoreCategory']]],
  ['definition_20changes_19',['Forcing GameAttributes to Update when Their Definition Changes',['../_persistent_data.html#GameAttributeCompareOptions',1,'']]],
  ['definition_20file_20',['Module Definition File',['../_creating_playfield_module.html#PlayfieldModuleDefinitionFile',1,'']]],
  ['definition_20files_21',['Example Module Definition Files',['../_creating_playfield_module.html#ModuleDefinitionExample',1,'']]],
  ['deflections_22',['Deflections',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_deflections.html',1,'Multimorphic::P3App::GUI']]],
  ['delay_23',['delay',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_mode.html#affbb9957ad13ac2f8d77b2d413f706c8',1,'Multimorphic::NetProcMachine::Machine::Mode']]],
  ['delayedguiinsertscript_24',['delayedGUIInsertScript',['../struct_multimorphic_1_1_p3_app_1_1_modes_1_1delayed_g_u_i_insert_script.html',1,'Multimorphic::P3App::Modes']]],
  ['delayedledscript_25',['delayedLEDScript',['../struct_multimorphic_1_1_net_proc_machine_1_1_l_e_ds_1_1delayed_l_e_d_script.html',1,'Multimorphic::NetProcMachine::LEDs']]],
  ['delayedsound_26',['DelayedSound',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_delayed_sound.html',1,'Multimorphic::P3App::GUI']]],
  ['delayfrom_27',['delayFrom',['../class_multimorphic_1_1_p3_s_a_1_1_g_u_i_1_1_follow_up_audio_clip_group.html#a7e87ed436224b32f5bc0212ef03d6a26',1,'Multimorphic::P3SA::GUI::FollowUpAudioClipGroup']]],
  ['deleteclip_28',['deleteClip',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_1_1_alphabet_menu.html#ad704ee1caedb4e7256933320b465828f',1,'Multimorphic.P3App.GUI.Menu.AlphabetMenu.deleteClip'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_text_selector.html#a9696dad8131dc63179c4655138a57c7e',1,'Multimorphic.P3App.GUI.Selector.TextSelector.deleteClip']]],
  ['dependentswitchentry_29',['DependentSwitchEntry',['../class_multimorphic_1_1_net_proc_machine_1_1_config_1_1_dependent_switch_entry.html',1,'Multimorphic::NetProcMachine::Config']]],
  ['deploy_30',['Preparing To Deploy',['../_deployment.html#PreparingToDeploy',1,'']]],
  ['deploying_20to_20your_20p3_20for_20testing_31',['Deploying To Your P3 For Testing',['../_deployment.html#ToP3',1,'']]],
  ['deployment_32',['Deployment',['../_deployment.html',1,'']]],
  ['description_33',['description',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_category.html#ad0bfbcbeb5f1281630b3adbc0fcc62ee',1,'Multimorphic::P3App::Modes::Data::HighScoreCategory']]],
  ['destroybuttonhandling_34',['DestroyButtonHandling',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_base.html#a784a43731c1f7005b0520b26f83674b9',1,'Multimorphic::P3App::GUI::MenuBase']]],
  ['detecting_20ball_20hits_35',['Detecting Ball Hits',['../_physical_features.html#DetectingBallsHittingWalls',1,'']]],
  ['detecting_20balls_20shot_20into_20a_20troughlauncher_36',['Detecting Balls Shot Into a TroughLauncher',['../_physical_features.html#TroughLauncherBallEntry',1,'']]],
  ['detecting_20balls_20shot_20into_20scoops_37',['Detecting Balls Shot Into Scoops',['../_physical_features.html#DetectingBallsInScoops',1,'']]],
  ['detecting_20playfield_20shots_38',['Detecting Playfield Shots',['../_physical_features.html#DetectingShots',1,'']]],
  ['detection_39',['Ball Collision Detection',['../_g_u_i_layer.html#CollisionDetection',1,'']]],
  ['develop_20my_20app_40',['Can I use Unity version x.y.z to develop my app?',['../_f_a_q.html#Unity5',1,'']]],
  ['developing_20the_20dll_41',['Developing The DLL',['../_creating_playfield_module.html#PlayfieldModuleDriverDLL',1,'']]],
  ['development_20machine_42',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['device_43',['Playfield Module USB Device',['../_creating_playfield_module.html#PlayfieldModuleUSBDevice',1,'']]],
  ['diagnostics_44',['Module Driver Diagnostics',['../_creating_playfield_module.html#ModuleDriverDiagnostics',1,'']]],
  ['directory_20structure_45',['Directory Structure',['../_deployment.html#DirectoryStructure',1,'']]],
  ['disable_46',['Disable',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_driver.html#a6ac29b823e33bcf430e8c74af568c16a',1,'Multimorphic.NetProcMachine.Machine.Driver.Disable()'],['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_virtual_driver.html#add929f7ec6efa5acbd5a1408e10b9526',1,'Multimorphic.NetProcMachine.Machine.VirtualDriver.Disable()']]],
  ['disabling_20backbox_20colors_20mode_47',['Disabling Backbox Colors Mode',['../_game_management.html#DisablingBackboxColorsMode',1,'']]],
  ['disabling_20bonus_20mode_48',['Disabling Bonus Mode',['../_game_management.html#DisablingBonusMode',1,'']]],
  ['disabling_20high_20scores_20mode_49',['Disabling High Scores Mode',['../_game_management.html#DisablingHighScoresMode',1,'']]],
  ['disabling_20tilt_20handling_50',['Disabling Tilt Handling',['../_game_management.html#DisablingTiltHandling',1,'']]],
  ['disallowedforrestoredgames_51',['disallowedForRestoredGames',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_category.html#a6984bdbf4ae38debf2126f794d826755',1,'Multimorphic::P3App::Modes::Data::HighScoreCategory']]],
  ['disallowfromrestoredgames_52',['DisallowFromRestoredGames',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_category.html#a7d28197be9107abccb3c4bbce6f82c46',1,'Multimorphic::P3App::Modes::Data::HighScoreCategory']]],
  ['dispatch_5fdelayed_53',['dispatch_delayed',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_mode.html#a4deac35543cc495b4a43a91f0cd1d470',1,'Multimorphic::NetProcMachine::Machine::Mode']]],
  ['display_54',['Display',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_game_manager_mode.html#a4b58dce58e06fe9f7e1d8d62b5625af8',1,'Multimorphic::P3App::Modes::GameManagerMode']]],
  ['displaycontroller_55',['DisplayController',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_display_controller.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['displaying_20high_20score_20tables_56',['Displaying High Score Tables',['../_persistent_data.html#DisplayingHighScores',1,'']]],
  ['distancefromcamera_57',['distanceFromCamera',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_front_and_center.html#a4c5ef3b707ba3aaf120771ffcbadbd93',1,'Multimorphic::P3App::GUI::FrontAndCenter']]],
  ['distancefromtarget_58',['distanceFromTarget',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_item.html#a9b1b71027276c5b9f377f7249bc92a31',1,'Multimorphic.P3App.GUI.MenuItem.distanceFromTarget'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_selector_item.html#a518d9ec8cc4c5265584f093461a85d3d',1,'Multimorphic.P3App.GUI.Selector.SelectorItem.distanceFromTarget']]],
  ['dll_59',['DLL',['../_creating_playfield_module.html#PlayfieldModuleDriverDLL',1,'Developing The DLL'],['../_creating_playfield_module.html#ModuleDriverDLLComponents',1,'Main Components of a Module Driver DLL']]],
  ['dmd_5fevent_60',['dmd_event',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_machine_controller.html#a1e0adf35f17cf470b4bf0a237d006ce0',1,'Multimorphic::NetProcMachine::Machine::MachineController']]],
  ['dmdbuffer_61',['DMDBuffer',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_d_m_d_buffer.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['dmdframe_62',['DMDFrame',['../struct_multimorphic_1_1_net_proc_game_1_1dmd_1_1_d_m_d_frame.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['dmdglobals_63',['DMDGlobals',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_d_m_d_globals.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['dmdpoint_64',['DMDPoint',['../struct_multimorphic_1_1_net_proc_game_1_1dmd_1_1_d_m_d_point.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['dmdrect_65',['DMDRect',['../struct_multimorphic_1_1_net_proc_game_1_1dmd_1_1_d_m_d_rect.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['dmdsize_66',['DMDSize',['../struct_multimorphic_1_1_net_proc_game_1_1dmd_1_1_d_m_d_size.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['do_20i_20compile_20my_20app_20so_20i_20can_20run_20it_20on_20my_20development_20machine_67',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['do_20i_20start_20a_20game_20after_20running_20my_20app_68',['How do I start a game after running my app?',['../_f_a_q.html#StartingAGame',1,'']]],
  ['doneclip_69',['doneClip',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_1_1_alphabet_menu.html#afad90a4175e5d2c748f0d494521f887b',1,'Multimorphic.P3App.GUI.Menu.AlphabetMenu.doneClip'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_text_selector.html#a5539caa5d8e40c3071caeee35fb5fe6a',1,'Multimorphic.P3App.GUI.Selector.TextSelector.doneClip']]],
  ['dontgothroughthings_70',['DontGoThroughThings',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_dont_go_through_things.html',1,'Multimorphic::P3App::GUI']]],
  ['drain_71',['Drain',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_drain.html',1,'Multimorphic::P3App::GUI']]],
  ['drainvalidatormode_72',['DrainValidatorMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_drain_validator_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['draw_73',['draw',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_font.html#a68eabb76f4f6b265a849aa570e93fd02',1,'Multimorphic::NetProcGame::dmd::Font']]],
  ['driver_74',['Driver',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_driver.html',1,'Multimorphic.NetProcMachine.Machine.Driver'],['../_creating_playfield_module.html#PlayfieldModuleDriver',1,'Playfield Module Driver']]],
  ['driver_75',['driver',['../class_multimorphic_1_1_net_proc_machine_1_1_lamps_1_1_lamp_show_track.html#a808d23b5d41e913de3050dc11124e2a3',1,'Multimorphic::NetProcMachine::Lamps::LampShowTrack']]],
  ['driver_20diagnostics_76',['Module Driver Diagnostics',['../_creating_playfield_module.html#ModuleDriverDiagnostics',1,'']]],
  ['driver_20dll_77',['Main Components of a Module Driver DLL',['../_creating_playfield_module.html#ModuleDriverDLLComponents',1,'']]],
  ['driver_20package_78',['Building the Module Driver Package',['../_creating_playfield_module.html#ModuleDriverPackage',1,'']]],
  ['driveralias_79',['DriverAlias',['../class_multimorphic_1_1_net_proc_machine_1_1_p_d_b_1_1_driver_alias.html',1,'Multimorphic::NetProcMachine::PDB']]],
  ['driveraliasentry_80',['DriverAliasEntry',['../class_multimorphic_1_1_net_proc_machine_1_1_config_1_1_driver_alias_entry.html',1,'Multimorphic::NetProcMachine::Config']]],
  ['driverglobalsentry_81',['DriverGlobalsEntry',['../class_multimorphic_1_1_net_proc_machine_1_1_config_1_1_driver_globals_entry.html',1,'Multimorphic::NetProcMachine::Config']]],
  ['drivers_82',['Drivers',['../_physical_features.html#DriverActions',1,'']]],
  ['driving_20a_20flipper_83',['Manually Driving a Flipper',['../_physical_features.html#PulsingFlippers',1,'']]],
  ['driving_20bumpers_84',['Manually Driving Bumpers',['../_physical_features.html#DrivingBumpers',1,'']]],
  ['dummy_20launches_85',['Dummy Launches',['../_physical_features.html#DummyLaunches',1,'']]],
  ['dummylaunch_86',['DummyLaunch',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_ball_launcher.html#a33f5dd3e199d83acc3fd98ad78358bce',1,'Multimorphic::P3App::Modes::BallLauncher']]],
  ['during_20a_20game_87',['During A Game',['../_physical_features.html#ChangingFlipperStrength',1,'Changing Flipper Strength During A Game'],['../_physical_features.html#ResetFlipperStrength',1,'Resetting Flipper Strength During A Game']]]
];
