var searchData=
[
  ['game_0',['Game',['../_physical_features.html#ChangingFlipperStrength',1,'Changing Flipper Strength During A Game'],['../_customizing_your_game.html',1,'Customizing Your Game'],['../_physical_features.html#ResetFlipperStrength',1,'Resetting Flipper Strength During A Game']]],
  ['game_1',['What&apos;s a game?',['../_overview.html#WhatsAGame',1,'']]],
  ['game_20after_20running_20my_20app_2',['How do I start a game after running my app?',['../_f_a_q.html#StartingAGame',1,'']]],
  ['game_20content_3',['Adding Game Content',['../_adding_game_content.html',1,'']]],
  ['game_20features_4',['Basic Game Features',['../_customizing_your_game.html#BasicGameFeatures',1,'']]],
  ['game_20handling_5',['General Game Handling',['../_persistent_data.html#GeneralGameHandlingGameAttributes',1,'']]],
  ['game_20management_6',['Game Management',['../_game_management.html',1,'Game Management'],['../_customizing_your_game.html#GameManagement',1,'Game Management']]],
  ['game_20section_7',['Game Section',['../_creating_playfield_module.html#ModuleDefinitionGame',1,'']]],
  ['game_20so_20that_20it_20appears_20in_20the_20settings_20menu_8',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['gameattribute_9',['GameAttribute',['../class_multimorphic_1_1_p3_app_1_1_data_1_1_game_attribute.html',1,'Multimorphic::P3App::Data']]],
  ['gameattribute_20profiles_10',['Stock GameAttribute Profiles',['../_persistent_data.html#StockProfiles',1,'']]],
  ['gameattribute_20tostring_20methods_11',['Customizing GameAttribute ToString methods',['../_persistent_data.html#CustomAttributeToString',1,'']]],
  ['gameattribute_20values_12',['GameAttribute Values',['../_persistent_data.html#Read_GameAttribute',1,'Reading GameAttribute Values'],['../_persistent_data.html#Write_GameAttribute',1,'Saving GameAttribute Values']]],
  ['gameattributekeyandattrstruct_13',['GameAttributeKeyAndAttrStruct',['../struct_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_game_attribute_key_and_attr_struct.html',1,'Multimorphic::P3App::Modes::Data']]],
  ['gameattributemanagermode_14',['GameAttributeManagerMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_game_attribute_manager_mode.html',1,'Multimorphic::P3App::Modes::Data']]],
  ['gameattributes_15',['GameAttributes',['../_persistent_data.html#AppGameAttributes',1,'App-Specific GameAttributes'],['../_persistent_data.html#BackboxColorAttributes',1,'Backbox Color GameAttributes'],['../_persistent_data.html#UserDefinedGameAttribute',1,'Creating GameAttributes'],['../_persistent_data.html#CustomizingDefaultGameAttributes',1,'Customizing Default GameAttributes'],['../_persistent_data.html#DebugAttributes',1,'Debug GameAttributes'],['../_persistent_data.html#DefaultGameAttributes',1,'Default GameAttributes'],['../_persistent_data.html#GlobalGeneralAudioGameAttributes',1,'Global Audio GameAttributes'],['../_persistent_data.html#GlobalBallTrackingGameAttributes',1,'Global Ball Tracking GameAttributes'],['../_persistent_data.html#GlobalCoilsGameAttributes',1,'Global Coil GameAttributes'],['../_persistent_data.html#GlobalCreditsGameAttributes',1,'Global Credit GameAttributes'],['../_persistent_data.html#GlobalGameAttributes',1,'Global GameAttributes'],['../_persistent_data.html#GlobalGeneralGameplayGameAttributes',1,'Global Gameplay GameAttributes'],['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'Global General Config GameAttributes'],['../_persistent_data.html#GlobalGIGameAttributes',1,'Global General Illumination GameAttributes'],['../_persistent_data.html#GlobalLEDBrightnessGameAttributes',1,'Global LED Brightness GameAttributes'],['../_persistent_data.html#GlobalServoWSGameAttributes',1,'Global Servo Wall/Scoop GameAttributes'],['../_persistent_data.html#PlayfieldModuleLocalGameAttributes',1,'Playfield Module Local GameAttributes'],['../_persistent_data.html#PlayfieldModuleGameAttributes',1,'Playfield Module-Specific GameAttributes'],['../_persistent_data.html#RedemptionAttributes',1,'Redemption GameAttributes'],['../_persistent_data.html#ReplayAttributes',1,'Replay GameAttributes']]],
  ['gameattributes_20from_20gui_20scripts_16',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['gameattributes_20to_20update_20when_20their_20definition_20changes_17',['Forcing GameAttributes to Update when Their Definition Changes',['../_persistent_data.html#GameAttributeCompareOptions',1,'']]],
  ['gameintro_18',['GameIntro',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_base_game_mode.html#a15cfb49b7335b87add6fe04f23adf4b9',1,'Multimorphic::P3App::Modes::BaseGameMode']]],
  ['gamemanagermode_19',['GameManagerMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_game_manager_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['gamemanagermode_20',['gameManagerMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_base_game_mode.html#aacf6cebaf577be2a68066fcc4daa4bd3',1,'Multimorphic::P3App::Modes::BaseGameMode']]],
  ['gamemode_21',['GameMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_game_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['gameplay_20gameattributes_22',['Global Gameplay GameAttributes',['../_persistent_data.html#GlobalGeneralGameplayGameAttributes',1,'']]],
  ['games_23',['Games',['../_game_management.html#BaseGameMode',1,'Base Mode for all Games'],['../_additional_platform_features.html#TeamGames',1,'Team Games']]],
  ['gate_24',['Gate',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_gate.html',1,'Multimorphic::P3App::GUI']]],
  ['gatesub_25',['GateSub',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_gate_sub.html',1,'Multimorphic::P3App::GUI']]],
  ['general_20config_20gameattributes_26',['Global General Config GameAttributes',['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'']]],
  ['general_20game_20handling_27',['General Game Handling',['../_persistent_data.html#GeneralGameHandlingGameAttributes',1,'']]],
  ['general_20illumination_20gameattributes_28',['Global General Illumination GameAttributes',['../_persistent_data.html#GlobalGIGameAttributes',1,'']]],
  ['get_5fevents_29',['get_events',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_machine_controller.html#a46ca9817f447b4580cbcd96f5f974a48',1,'Multimorphic::NetProcMachine::Machine::MachineController']]],
  ['getallbeams_30',['getAllBeams',['../class_multimorphic_1_1_p3_1_1_grid_1_1_grid.html#a0320b184355cff4a33f193ceb2478069',1,'Multimorphic::P3::Grid::Grid']]],
  ['getassetnamesfromassetbundle_31',['GetAssetNamesFromAssetBundle',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_asset_pack.html#a8c0b9c923a9698571fe3585328ddd7ae',1,'Multimorphic::P3App::GUI::AssetPack']]],
  ['getattributeitemfromstringandindex_32',['GetAttributeItemFromStringAndIndex',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_scores_mode.html#a018149dc8536484fca7632672e6f3926',1,'Multimorphic::P3App::Modes::Data::HighScoresMode']]],
  ['getavailabletimezones_33',['GetAvailableTimeZones',['../class_multimorphic_1_1_p3_1_1_tools_1_1_time.html#a0d68acb703572f3c47fe8a7f7b8717e3',1,'Multimorphic::P3::Tools::Time']]],
  ['getballlocations_5fsafe_34',['getBallLocations_safe',['../class_multimorphic_1_1_p3_1_1_grid_1_1_ball_tracker.html#a49244b3d4fe32bf327f8dd262b416017',1,'Multimorphic::P3::Grid::BallTracker']]],
  ['getballpositionandvelocity_35',['GetBallPositionAndVelocity',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_p3_controller_interface.html#af225dfc640d61c9d504dcdb79193382b',1,'Multimorphic::P3App::GUI::P3ControllerInterface']]],
  ['getballpositionandvelocity_5fsafe_36',['getBallPositionAndVelocity_safe',['../class_multimorphic_1_1_p3_1_1_grid_1_1_ball_tracker.html#abba7414d13aade243f14cf43e8f8a607',1,'Multimorphic::P3::Grid::BallTracker']]],
  ['gethighscoreitems_37',['GetHighScoreItems',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_high_score_display_data.html#ab3451e55b50e24f21df8329a6fb7371a',1,'Multimorphic::P3App::Modes::Data::HighScoreDisplayData']]],
  ['getmastervolumelevel_38',['GetMasterVolumeLevel',['../class_multimorphic_1_1_p3_s_a_1_1_g_u_i_1_1_p3_s_a_audio.html#a7f5974eae6dfaba149d97b5127776953',1,'Multimorphic::P3SA::GUI::P3SAAudio']]],
  ['getnetworkname_39',['GetNetworkName',['../class_multimorphic_1_1_p3_1_1_tools_1_1_network.html#a015311b035219f9694c46ee0e1832334',1,'Multimorphic::P3::Tools::Network']]],
  ['getnetworktime_40',['GetNetworkTime',['../class_multimorphic_1_1_p3_1_1_tools_1_1_time.html#a0e2dd0f905e31f9151749eba06829cde',1,'Multimorphic::P3::Tools::Time']]],
  ['getnumcreditsfordisplay_41',['GetNumCreditsForDisplay',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_money_mode.html#ad68404b29879a607a4b65b17bd472439',1,'Multimorphic::P3App::Modes::MoneyMode']]],
  ['getnummechs_42',['GetNumMechs',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_playfield_module_1_1_playfield_module_controller.html#a2e41de0faa291c4f9b9dfd0c6106c14e',1,'Multimorphic.P3App.Modes.PlayfieldModule.PlayfieldModuleController.GetNumMechs()'],['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_playfield_module_1_1_playfield_module_manager.html#adee94ba17fdb48f8ab35e26d63cc54ed',1,'Multimorphic.P3App.Modes.PlayfieldModule.PlayfieldModuleManager.GetNumMechs()']]],
  ['getplayername_43',['GetPlayerName',['../class_multimorphic_1_1_p3_app_1_1_data_1_1_data_manager.html#a907d076816118fbeb8d869a992efe940',1,'Multimorphic::P3App::Data::DataManager']]],
  ['getplaylistmastervolumelevel_44',['GetPlaylistMasterVolumeLevel',['../class_multimorphic_1_1_p3_s_a_1_1_g_u_i_1_1_p3_s_a_audio.html#a2f8b7c86b17dbc79f8f843b733abe2b6',1,'Multimorphic::P3SA::GUI::P3SAAudio']]],
  ['getprojectedpoint_45',['GetProjectedPoint',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_p3_aware.html#a1e7f9f27d136fb331a90f42bf732da33',1,'Multimorphic.P3App.GUI.P3Aware.GetProjectedPoint(Plane plane, Vector3 point, out Vector3 projectedPoint)'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_p3_aware.html#a6512a99898050c74786d9ca1c0599067',1,'Multimorphic.P3App.GUI.P3Aware.GetProjectedPoint(Plane plane, GameObject obj, out Vector3 projectedPoint)'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_physical_interaction.html#af2ef87953e402b0a417b6be9dbb08283',1,'Multimorphic.P3App.GUI.PhysicalInteraction.GetProjectedPoint(Plane plane, Vector3 point, out Vector3 projectedPoint)'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_physical_interaction.html#a046a3629ce6102e886f853bd1f69905a',1,'Multimorphic.P3App.GUI.PhysicalInteraction.GetProjectedPoint(Plane plane, GameObject obj, out Vector3 projectedPoint)']]],
  ['getprojectedpointunderball_46',['GetProjectedPointUnderBall',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_p3_aware.html#a19d8135441fcadc22788cf11e2f2eb74',1,'Multimorphic.P3App.GUI.P3Aware.GetProjectedPointUnderBall()'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_physical_interaction.html#a0d9d9e1fa4c0289be14fd3e4a875c68f',1,'Multimorphic.P3App.GUI.PhysicalInteraction.GetProjectedPointUnderBall()']]],
  ['getprojectedpointunderpredictiveball_47',['GetProjectedPointUnderPredictiveBall',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_p3_aware.html#a8480c8f47ea23e9762fe5ad47740399e',1,'Multimorphic::P3App::GUI::P3Aware']]],
  ['gettime_48',['GetTime',['../class_multimorphic_1_1_p3_1_1_tools_1_1_time.html#acbccabc3f4612d49b74f129ddf599f4c',1,'Multimorphic.P3.Tools.Time.GetTime()'],['../class_multimorphic_1_1_net_proc_machine_1_1_tools_1_1_time.html#a43c02dadffb66bdfbfe212235279236c',1,'Multimorphic.NetProcMachine.Tools.Time.GetTime()']]],
  ['gettimezone_49',['GetTimeZone',['../class_multimorphic_1_1_p3_1_1_tools_1_1_time.html#a0df444bdb8bf74a0bad6d7d847767c0a',1,'Multimorphic::P3::Tools::Time']]],
  ['getting_20started_50',['Getting Started',['../_getting_started.html',1,'']]],
  ['getwifireception_51',['GetWifiReception',['../class_multimorphic_1_1_p3_1_1_tools_1_1_network.html#ae1af0cfa463cd9f4a7ad904c9b546b24',1,'Multimorphic::P3::Tools::Network']]],
  ['gi_52',['GI',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_machine_controller.html#ac38fac49a1854ef8ed50a3599cc02e7a',1,'Multimorphic::NetProcMachine::Machine::MachineController']]],
  ['giconfigfileentry_53',['GIConfigFileEntry',['../class_multimorphic_1_1_net_proc_machine_1_1_config_1_1_g_i_config_file_entry.html',1,'Multimorphic::NetProcMachine::Config']]],
  ['global_20audio_20gameattributes_54',['Global Audio GameAttributes',['../_persistent_data.html#GlobalGeneralAudioGameAttributes',1,'']]],
  ['global_20ball_20tracking_20gameattributes_55',['Global Ball Tracking GameAttributes',['../_persistent_data.html#GlobalBallTrackingGameAttributes',1,'']]],
  ['global_20coil_20gameattributes_56',['Global Coil GameAttributes',['../_persistent_data.html#GlobalCoilsGameAttributes',1,'']]],
  ['global_20credit_20gameattributes_57',['Global Credit GameAttributes',['../_persistent_data.html#GlobalCreditsGameAttributes',1,'']]],
  ['global_20gameattributes_58',['Global GameAttributes',['../_persistent_data.html#GlobalGameAttributes',1,'']]],
  ['global_20gameplay_20gameattributes_59',['Global Gameplay GameAttributes',['../_persistent_data.html#GlobalGeneralGameplayGameAttributes',1,'']]],
  ['global_20general_20config_20gameattributes_60',['Global General Config GameAttributes',['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'']]],
  ['global_20general_20illumination_20gameattributes_61',['Global General Illumination GameAttributes',['../_persistent_data.html#GlobalGIGameAttributes',1,'']]],
  ['global_20led_20brightness_20gameattributes_62',['Global LED Brightness GameAttributes',['../_persistent_data.html#GlobalLEDBrightnessGameAttributes',1,'']]],
  ['global_20servo_20wall_20scoop_20gameattributes_63',['Global Servo Wall/Scoop GameAttributes',['../_persistent_data.html#GlobalServoWSGameAttributes',1,'']]],
  ['globalsettingsmode_64',['GlobalSettingsMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_global_settings_mode.html',1,'Multimorphic::P3App::Modes::Data']]],
  ['gotomenuitemwithcaption_65',['GoToMenuItemWithCaption',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_base.html#a1759008ffb3b48bd8ebcfc56a284a564',1,'Multimorphic::P3App::GUI::MenuBase']]],
  ['gotorootwhenenabled_66',['goToRootWhenEnabled',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_base.html#a68f751d468bf7de238e570a64d0b93f5',1,'Multimorphic.P3App.GUI.MenuBase.goToRootWhenEnabled'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_selector.html#af9444737b91ca2d0d7dc0d78d3f5b5cb',1,'Multimorphic.P3App.GUI.Selector.Selector.goToRootWhenEnabled']]],
  ['gotoselectoritemwithcaption_67',['GoToSelectorItemWithCaption',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_selector.html#af53426063fd9b67abd01007542b9c1fa',1,'Multimorphic::P3App::GUI::Selector::Selector']]],
  ['grid_68',['Grid',['../class_multimorphic_1_1_p3_1_1_grid_1_1_grid.html',1,'Multimorphic.P3.Grid.Grid'],['../class_multimorphic_1_1_p3_1_1_grid_1_1_grid.html#ae3fcd0c0739d4eab9d3edaf1236fa019',1,'Multimorphic.P3.Grid.Grid.Grid()']]],
  ['griddefinition_69',['GridDefinition',['../class_multimorphic_1_1_p3_1_1_grid_1_1_grid_definition.html',1,'Multimorphic::P3::Grid']]],
  ['griddefinitionloader_70',['GridDefinitionLoader',['../class_multimorphic_1_1_p3_1_1_grid_1_1_grid_definition_loader.html',1,'Multimorphic::P3::Grid']]],
  ['gridgenerator_71',['GridGenerator',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_grid_generator.html',1,'Multimorphic::P3App::GUI']]],
  ['gridinterfacemode_72',['GridInterfaceMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_grid_interface_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['gridmenu_73',['GridMenu',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_grid_menu.html',1,'Multimorphic::P3App::GUI']]],
  ['gridshapedselector_74',['GridShapedSelector',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_grid_shaped_selector.html',1,'Multimorphic::P3App::GUI::Selector']]],
  ['groupedlayer_75',['GroupedLayer',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_grouped_layer.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['gui_76',['The Layers: Mode and GUI',['../_app_structure.html#ModeGUI',1,'']]],
  ['gui_20example_3a_20a_20moving_20virtual_20target_77',['A GUI Example: A Moving Virtual Target',['../_g_u_i_layer.html#UIMovingTargetExample',1,'']]],
  ['gui_20layer_78',['GUI Layer',['../_g_u_i_layer.html#EventsInGUILayer',1,'Events in GUI Layer'],['../_g_u_i_layer.html',1,'The GUI Layer']]],
  ['gui_20scripts_79',['Receiving Mode Events In GUI Scripts',['../_g_u_i_layer.html#ReceivingModeEventsInGUI',1,'']]],
  ['gui_20scripts_80',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['guiinsert_81',['GUIInsert',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_g_u_i_insert.html',1,'Multimorphic::P3App::Modes']]],
  ['guiinsertcolorchanger_82',['GUIInsertColorChanger',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_g_u_i_insert_color_changer.html',1,'Multimorphic::P3App::GUI']]],
  ['guiinsertcommand_83',['GUIInsertCommand',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_g_u_i_insert_command.html',1,'Multimorphic::P3App::Modes']]],
  ['guiinsertcontrollermode_84',['GUIInsertControllerMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_g_u_i_insert_controller_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['guiinserthelpers_85',['GUIInsertHelpers',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_g_u_i_insert_helpers.html',1,'Multimorphic::P3App::Modes']]],
  ['guiinsertscript_86',['GUIInsertScript',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_g_u_i_insert_script.html',1,'Multimorphic::P3App::Modes']]],
  ['guitextposition_87',['GUITextPosition',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_g_u_i_text_position.html',1,'Multimorphic::P3App::GUI']]],
  ['guitexttogameobject_88',['GUITextToGameObject',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_g_u_i_text_to_game_object.html',1,'Multimorphic::P3App::GUI']]],
  ['guitomode_20events_89',['List of GUIToMode Events',['../_event_list.html#GUIToModeEventList',1,'']]],
  ['guitomodeseventmanager_90',['GUIToModesEventManager',['../class_multimorphic_1_1_p3_1_1_p3_controller.html#ae7bb6e25ff966270d4d8f58762c7abbc',1,'Multimorphic::P3::P3Controller']]]
];
