var searchData=
[
  ['can_20i_20access_20gameattributes_20from_20gui_20scripts_0',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['can_20i_20add_20a_20new_20setting_20for_20my_20game_20so_20that_20it_20appears_20in_20the_20settings_20menu_1',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['can_20i_20use_20unity_20version_20x_20y_20z_20to_20develop_20my_20app_2',['Can I use Unity version x.y.z to develop my app?',['../_f_a_q.html#Unity5',1,'']]],
  ['can_20run_20it_20on_20my_20development_20machine_3',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['categories_4',['High Score Categories',['../_persistent_data.html#HighScoreCategories',1,'']]],
  ['changes_5',['Forcing GameAttributes to Update when Their Definition Changes',['../_persistent_data.html#GameAttributeCompareOptions',1,'']]],
  ['changing_20flipper_20strength_20during_20a_20game_6',['Changing Flipper Strength During A Game',['../_physical_features.html#ChangingFlipperStrength',1,'']]],
  ['chase_7',['Example: Chase',['../_physical_features.html#LEDScriptsChase',1,'']]],
  ['choosing_20your_20appcode_8',['Choosing Your AppCode',['../_creating_app.html#ChoosingAppCode',1,'']]],
  ['classing_20from_20existing_20modes_9',['Sub-classing From Existing Modes',['../_mode_layer.html#Sub-classing',1,'']]],
  ['code_10',['Custom Launch Code',['../_creating_playfield_module.html#CustomLaunchCode',1,'']]],
  ['code_20when_20saving_20operator_20settings_11',['Run Code When Saving Operator Settings',['../_persistent_data.html#RunCodeUponSavingGameAttribute',1,'']]],
  ['coil_20gameattributes_12',['Global Coil GameAttributes',['../_persistent_data.html#GlobalCoilsGameAttributes',1,'']]],
  ['coils_20section_13',['Coils Section',['../_creating_playfield_module.html#ModuleDefinitionCoils',1,'']]],
  ['collision_20detection_14',['Ball Collision Detection',['../_g_u_i_layer.html#CollisionDetection',1,'']]],
  ['color_20gameattributes_15',['Backbox Color GameAttributes',['../_persistent_data.html#BackboxColorAttributes',1,'']]],
  ['colors_20mode_16',['Disabling Backbox Colors Mode',['../_game_management.html#DisablingBackboxColorsMode',1,'']]],
  ['comparisons_17',['Initiating High Score Comparisons',['../_persistent_data.html#HighScoreComparisons',1,'']]],
  ['compile_20my_20app_20so_20i_20can_20run_20it_20on_20my_20development_20machine_18',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['components_20of_20a_20module_20driver_20dll_19',['Main Components of a Module Driver DLL',['../_creating_playfield_module.html#ModuleDriverDLLComponents',1,'']]],
  ['concepts_20',['Fundamental Concepts',['../_overview.html#FundamentalConcepts',1,'']]],
  ['config_20gameattributes_21',['Global General Config GameAttributes',['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'']]],
  ['configuration_22',['Configuration',['../_persistent_data.html#BallSearchGameAttributes',1,'Ball Search Configuration'],['../_persistent_data.html#ButtonGameAttributes',1,'Button Configuration'],['../_persistent_data.html#FeatureMenuGameAttributes',1,'Feature Menu Configuration'],['../_persistent_data.html#SlingShotGameAttributes',1,'Slingshot Configuration'],['../_persistent_data.html#TiltGameAttributes',1,'Tilt Configuration']]],
  ['configuring_20your_20application_23',['Configuring Your Application',['../_creating_app.html#AppConfiguration',1,'']]],
  ['connections_24',['Bluetooth Connections',['../_additional_platform_features.html#Bluetooth',1,'']]],
  ['content_25',['Adding Game Content',['../_adding_game_content.html',1,'']]],
  ['controller_26',['Scene Controller',['../_g_u_i_layer.html#SceneController',1,'']]],
  ['controlling_20bumpers_27',['Controlling Bumpers',['../_physical_features.html#ControllingBumpers',1,'']]],
  ['controlling_20flippers_28',['Controlling Flippers',['../_physical_features.html#Flippers',1,'']]],
  ['controlling_20physical_20features_29',['Controlling Physical Features',['../_physical_features.html',1,'']]],
  ['coordinate_20system_30',['Coordinate System',['../_creating_playfield_module.html#ModuleDefinitionCoords',1,'']]],
  ['creating_20gameattributes_31',['Creating GameAttributes',['../_persistent_data.html#UserDefinedGameAttribute',1,'']]],
  ['creating_20log_20messages_32',['Creating log messages',['../_logging_page.html#CreatingLogs',1,'']]],
  ['creating_20your_20app_33',['Creating Your App',['../_creating_app.html',1,'']]],
  ['creating_20your_20playfield_20module_34',['Creating Your Playfield Module',['../_creating_playfield_module.html',1,'']]],
  ['creating_20your_20project_35',['Creating Your Project',['../_creating_app.html#CreatingYourProject',1,'']]],
  ['credit_20gameattributes_36',['Global Credit GameAttributes',['../_persistent_data.html#GlobalCreditsGameAttributes',1,'']]],
  ['credit_20handling_37',['Credit Handling',['../_persistent_data.html#CreditsGameAttributes',1,'']]],
  ['credits_38',['Credits',['../_customizing_your_game.html#Credits',1,'']]],
  ['custom_20launch_20code_39',['Custom Launch Code',['../_creating_playfield_module.html#CustomLaunchCode',1,'']]],
  ['customizing_20default_20gameattributes_40',['Customizing Default GameAttributes',['../_persistent_data.html#CustomizingDefaultGameAttributes',1,'']]],
  ['customizing_20gameattribute_20tostring_20methods_41',['Customizing GameAttribute ToString methods',['../_persistent_data.html#CustomAttributeToString',1,'']]],
  ['customizing_20your_20game_42',['Customizing Your Game',['../_customizing_your_game.html',1,'']]]
];
