var searchData=
[
  ['p3_0',['P3',['../_overview.html',1,'Overview of the P3'],['../_overview.html#UnityAndTheP3',1,'Unity and the P3']]],
  ['p3_20app_1',['Structure of a P3 App',['../_app_structure.html',1,'']]],
  ['p3_20application_20sample_2',['The P3 Application Sample',['../_getting_started.html#SampleApp',1,'']]],
  ['p3_20for_20testing_3',['Deploying To Your P3 For Testing',['../_deployment.html#ToP3',1,'']]],
  ['p3_20modes_4',['An Overview of P3 Modes',['../_mode_layer.html#ModeOverview',1,'']]],
  ['p3_20sdk_5',['Introduction to the P3 SDK',['../_introduction.html',1,'']]],
  ['p3app_20balllauncher_6',['Initializing The Multimorphic.P3App.BallLauncher',['../_physical_features.html#InitializeBallLauncher',1,'']]],
  ['p3aware_20objects_7',['P3Aware Objects',['../_g_u_i_layer.html#P3AwareObjects',1,'']]],
  ['p3playfield_8',['P3Playfield',['../_g_u_i_layer.html#P3Playfield',1,'']]],
  ['package_9',['Building the Module Driver Package',['../_creating_playfield_module.html#ModuleDriverPackage',1,'']]],
  ['paths_10',['Ball Paths',['../_physical_features.html#DetectingShotsViaBallPaths',1,'']]],
  ['pausing_20the_20flippers_11',['Pausing The Flippers',['../_physical_features.html#PauseFlippers',1,'']]],
  ['persistent_20data_12',['Persistent Data',['../_persistent_data.html',1,'ModeLayer']]],
  ['physical_20features_13',['Controlling Physical Features',['../_physical_features.html',1,'']]],
  ['platform_20features_14',['Additional Platform Features',['../_additional_platform_features.html',1,'']]],
  ['play_15',['Launching Balls Into Play',['../_physical_features.html#TroughLaunching',1,'']]],
  ['player_20data_16',['Player Data',['../_player_data.html',1,'Player Data'],['../_player_data.html#RetrievingPlayerData',1,'Retrieving Player Data'],['../_player_data.html#SavingPlayerData',1,'Saving Player Data']]],
  ['player_20profile_20events_17',['Player Profile Events',['../_additional_platform_features.html#EventBasedPlayerProfileManagement',1,'']]],
  ['player_20profiles_18',['Player Profiles',['../_additional_platform_features.html#PlayerProfiles',1,'']]],
  ['player_20removal_19',['Player Removal',['../_additional_platform_features.html#PlayerRemoval',1,'']]],
  ['player_20specific_20settings_20',['Player-specific Settings',['../_additional_platform_features.html#PlayerProfileSettings',1,'']]],
  ['players_21',['Restarts and Removing Players',['../_additional_platform_features.html#RestartsAndRemovingPlayers',1,'']]],
  ['playfield_20module_22',['Creating Your Playfield Module',['../_creating_playfield_module.html',1,'']]],
  ['playfield_20module_20driver_23',['Playfield Module Driver',['../_creating_playfield_module.html#PlayfieldModuleDriver',1,'']]],
  ['playfield_20module_20identifier_24',['Playfield Module Identifier',['../_creating_playfield_module.html#PlayfieldModuleID',1,'']]],
  ['playfield_20module_20local_20gameattributes_25',['Playfield Module Local GameAttributes',['../_persistent_data.html#PlayfieldModuleLocalGameAttributes',1,'']]],
  ['playfield_20module_20specific_20gameattributes_26',['Playfield Module-Specific GameAttributes',['../_persistent_data.html#PlayfieldModuleGameAttributes',1,'']]],
  ['playfield_20module_20usb_20device_27',['Playfield Module USB Device',['../_creating_playfield_module.html#PlayfieldModuleUSBDevice',1,'']]],
  ['playfield_20moduleid_28',['Obtaining A Unique Playfield ModuleID',['../_deployment.html#ObtainingModuleID',1,'']]],
  ['playfield_20shots_29',['Detecting Playfield Shots',['../_physical_features.html#DetectingShots',1,'']]],
  ['popup_20scores_30',['Popup Scores',['../_adding_game_content.html#PopupScores',1,'']]],
  ['power_20relay_20off_20at_20startup_31',['Keeping Power Relay Off At Startup',['../_game_management.html#KeepingPowerRelayOffAtStartup',1,'']]],
  ['preparing_20to_20deploy_32',['Preparing To Deploy',['../_deployment.html#PreparingToDeploy',1,'']]],
  ['profile_20events_33',['Player Profile Events',['../_additional_platform_features.html#EventBasedPlayerProfileManagement',1,'']]],
  ['profiles_34',['Profiles',['../_additional_platform_features.html#PlayerProfiles',1,'Player Profiles'],['../_persistent_data.html#StockProfiles',1,'Stock GameAttribute Profiles']]],
  ['programming_35',['Introduction to Mode Programming',['../_mode_layer.html#ModeIntr',1,'']]],
  ['project_36',['Creating Your Project',['../_creating_app.html#CreatingYourProject',1,'']]],
  ['pulsing_20a_20bumper_37',['Pulsing a Bumper',['../_physical_features.html#PulsingBumpers',1,'']]]
];
