var searchData=
[
  ['tables_0',['Displaying High Score Tables',['../_persistent_data.html#DisplayingHighScores',1,'']]],
  ['target_1',['A GUI Example: A Moving Virtual Target',['../_g_u_i_layer.html#UIMovingTargetExample',1,'']]],
  ['target_2',['target',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_menu_item.html#a1492a40403d5512e6f40e3123500ac79',1,'Multimorphic.P3App.GUI.MenuItem.target'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_selector_item.html#a52e08756a5e22a1619c161b435a260fe',1,'Multimorphic.P3App.GUI.Selector.SelectorItem.target']]],
  ['target_5fx_3',['target_x',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_layer.html#ab8d84a7d312ea8f9a59c73b015527919',1,'Multimorphic::NetProcGame::dmd::Layer']]],
  ['target_5fx_5foffset_4',['target_x_offset',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_layer.html#a3d80d337a21c9de8f6e4de856426ce3d',1,'Multimorphic::NetProcGame::dmd::Layer']]],
  ['target_5fy_5',['target_y',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_layer.html#a001ab7cdfa6ab0feea626b7b93f1db03',1,'Multimorphic::NetProcGame::dmd::Layer']]],
  ['target_5fy_5foffset_6',['target_y_offset',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_layer.html#a3ab1f83faf837bc5eff0e9a7d9755dd9',1,'Multimorphic::NetProcGame::dmd::Layer']]],
  ['team_20games_7',['Team Games',['../_additional_platform_features.html#TeamGames',1,'']]],
  ['teamgamemanagermode_8',['TeamGameManagerMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_data_1_1_team_game_manager_mode.html',1,'Multimorphic::P3App::Modes::Data']]],
  ['technology_20stack_9',['The Technology Stack',['../_overview.html#TechnologyStack',1,'']]],
  ['terminology_10',['Terminology',['../_overview.html#Terminology',1,'']]],
  ['testing_11',['Deploying To Your P3 For Testing',['../_deployment.html#ToP3',1,'']]],
  ['textanimated_12',['TextAnimated',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_text_animated.html',1,'Multimorphic::P3App::GUI']]],
  ['textborder_13',['TextBorder',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_text_border.html',1,'Multimorphic::P3App::GUI']]],
  ['textdisplay_14',['TextDisplay',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_text_display.html',1,'Multimorphic::P3App::GUI']]],
  ['texteditor_15',['TextEditor',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_text_editor.html',1,'Multimorphic::P3App::GUI']]],
  ['textlayer_16',['TextLayer',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_text_layer.html',1,'Multimorphic::NetProcGame::dmd']]],
  ['textreceiver_17',['TextReceiver',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_text_receiver.html',1,'Multimorphic::P3App::GUI']]],
  ['textselector_18',['TextSelector',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_text_selector.html',1,'Multimorphic::P3App::GUI::Selector']]],
  ['textselectordata_19',['TextSelectorData',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_selector_1_1_text_selector_data.html',1,'Multimorphic::P3App::GUI::Selector']]],
  ['textselectormode_20',['TextSelectorMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_text_selector_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['that_20it_20appears_20in_20the_20settings_20menu_21',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['the_20assets_20folder_20structure_22',['The Assets Folder Structure',['../_folders_namespaces.html#AssetsFolder',1,'']]],
  ['the_20bumpers_23',['Enabling the Bumpers',['../_physical_features.html#EnablingBumpers',1,'']]],
  ['the_20dll_24',['Developing The DLL',['../_creating_playfield_module.html#PlayfieldModuleDriverDLL',1,'']]],
  ['the_20flippers_25',['Pausing The Flippers',['../_physical_features.html#PauseFlippers',1,'']]],
  ['the_20flippers_26',['Enabling the Flippers',['../_physical_features.html#EnablingFlippers',1,'']]],
  ['the_20frame_20rate_27',['Is there an easy way to see the frame rate?',['../_f_a_q.html#FrameRate',1,'']]],
  ['the_20framework_28',['The Framework',['../_app_structure.html#FrameworkAnalogy',1,'An Analogy For The Framework'],['../_mode_layer.html#IncludedModes',1,'Modes Included In The Framework']]],
  ['the_20gui_20layer_29',['The GUI Layer',['../_g_u_i_layer.html',1,'']]],
  ['the_20layers_3a_20mode_20and_20gui_30',['The Layers: Mode and GUI',['../_app_structure.html#ModeGUI',1,'']]],
  ['the_20mode_20layer_31',['The Mode Layer',['../_mode_layer.html',1,'']]],
  ['the_20module_20driver_20package_32',['Building the Module Driver Package',['../_creating_playfield_module.html#ModuleDriverPackage',1,'']]],
  ['the_20multimorphic_20p3app_20balllauncher_33',['Initializing The Multimorphic.P3App.BallLauncher',['../_physical_features.html#InitializeBallLauncher',1,'']]],
  ['the_20namespace_20structure_34',['The Namespace Structure',['../_folders_namespaces.html#NamespaceStructure',1,'']]],
  ['the_20p3_35',['the P3',['../_overview.html',1,'Overview of the P3'],['../_overview.html#UnityAndTheP3',1,'Unity and the P3']]],
  ['the_20p3_20application_20sample_36',['The P3 Application Sample',['../_getting_started.html#SampleApp',1,'']]],
  ['the_20p3_20sdk_37',['Introduction to the P3 SDK',['../_introduction.html',1,'']]],
  ['the_20settings_20menu_38',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['the_20simulator_39',['The Simulator',['../_getting_started.html#Simulator',1,'']]],
  ['the_20technology_20stack_40',['The Technology Stack',['../_overview.html#TechnologyStack',1,'']]],
  ['their_20definition_20changes_41',['Forcing GameAttributes to Update when Their Definition Changes',['../_persistent_data.html#GameAttributeCompareOptions',1,'']]],
  ['theory_20of_20operation_20of_20basegamemode_42',['Theory of Operation of BaseGameMode',['../_game_management.html#BaseGameModeOverview',1,'']]],
  ['there_20an_20easy_20way_20to_20see_20the_20frame_20rate_43',['Is there an easy way to see the frame rate?',['../_f_a_q.html#FrameRate',1,'']]],
  ['this_20kit_44',['What&apos;s Included In This Kit',['../_introduction.html#WhatsIncluded',1,'']]],
  ['tick_45',['tick',['../class_multimorphic_1_1_net_proc_machine_1_1_lamps_1_1_lamp_show.html#acee63d5de761a51c5941df67c4b9dd6f',1,'Multimorphic::NetProcMachine::Lamps::LampShow']]],
  ['tick_5fvirtual_5fdrivers_46',['tick_virtual_drivers',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_machine_controller.html#a99e3e4561409c97155851753ab180628',1,'Multimorphic::NetProcMachine::Machine::MachineController']]],
  ['ticketdispensemode_47',['TicketDispenseMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_ticket_dispense_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['tilt_20active_48',['Show End-of-Ball Bonus If Tilt Active',['../_game_management.html#ShowBonusEventIfTiltActive',1,'']]],
  ['tilt_20configuration_49',['Tilt Configuration',['../_persistent_data.html#TiltGameAttributes',1,'']]],
  ['tilt_20handling_50',['Tilt Handling',['../_game_management.html#DisablingTiltHandling',1,'Disabling Tilt Handling'],['../_customizing_your_game.html#Tilt',1,'Tilt Handling']]],
  ['tiltedmode_51',['TiltedMode',['../class_multimorphic_1_1_p3_s_a_1_1_modes_1_1_tilted_mode.html',1,'Multimorphic::P3SA::Modes']]],
  ['tiltmode_52',['TiltMode',['../class_multimorphic_1_1_p3_app_1_1_modes_1_1_tilt_mode.html',1,'Multimorphic::P3App::Modes']]],
  ['time_53',['Time',['../class_multimorphic_1_1_net_proc_machine_1_1_tools_1_1_time.html',1,'Multimorphic.NetProcMachine.Tools.Time'],['../class_multimorphic_1_1_p3_1_1_tools_1_1_time.html',1,'Multimorphic.P3.Tools.Time']]],
  ['timesincechange_54',['TimeSinceChange',['../class_multimorphic_1_1_net_proc_machine_1_1_machine_1_1_switch.html#a6c983deb83d9e06c11b4d40b37c81cf3',1,'Multimorphic::NetProcMachine::Machine::Switch']]],
  ['to_20deploy_55',['Preparing To Deploy',['../_deployment.html#PreparingToDeploy',1,'']]],
  ['to_20develop_20my_20app_56',['Can I use Unity version x.y.z to develop my app?',['../_f_a_q.html#Unity5',1,'']]],
  ['to_20hardware_57',['Mapping To Hardware',['../_creating_app.html#HardwareMapping',1,'']]],
  ['to_20mode_20programming_58',['Introduction to Mode Programming',['../_mode_layer.html#ModeIntr',1,'']]],
  ['to_20modes_59',['Sending Events To Modes',['../_g_u_i_layer.html#SendingGUIEventsToModes',1,'']]],
  ['to_20see_20the_20frame_20rate_60',['Is there an easy way to see the frame rate?',['../_f_a_q.html#FrameRate',1,'']]],
  ['to_20the_20p3_20sdk_61',['Introduction to the P3 SDK',['../_introduction.html',1,'']]],
  ['to_20troughlaunchers_62',['Request Access To TroughLaunchers',['../_physical_features.html#RequestTroughLaunchers',1,'']]],
  ['to_20update_20when_20their_20definition_20changes_63',['Forcing GameAttributes to Update when Their Definition Changes',['../_persistent_data.html#GameAttributeCompareOptions',1,'']]],
  ['to_20your_20p3_20for_20testing_64',['Deploying To Your P3 For Testing',['../_deployment.html#ToP3',1,'']]],
  ['tojson_65',['ToJSON',['../class_multimorphic_1_1_p3_1_1_config_1_1_p3_configuration.html#ad815346f3809fe5caf5cd5375ef5e3f8',1,'Multimorphic.P3.Config.P3Configuration.ToJSON()'],['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_p3_controller_interface_configuration.html#a8073d5a01f193496c6a94bc061ef5395',1,'Multimorphic.P3App.GUI.P3ControllerInterfaceConfiguration.ToJSON()'],['../class_multimorphic_1_1_net_proc_machine_1_1_config_1_1_machine_configuration.html#aec88026ec6a3f47b4c55c6256b787636',1,'Multimorphic.NetProcMachine.Config.MachineConfiguration.ToJSON()']]],
  ['tostring_20methods_66',['Customizing GameAttribute ToString methods',['../_persistent_data.html#CustomAttributeToString',1,'']]],
  ['tracking_67',['High Score Tracking',['../_customizing_your_game.html#HighScoreCheck',1,'']]],
  ['tracking_68',['tracking',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_font.html#a01368abf8a76b0e08be1940df5bb5233',1,'Multimorphic::NetProcGame::dmd::Font']]],
  ['tracking_20gameattributes_69',['Global Ball Tracking GameAttributes',['../_persistent_data.html#GlobalBallTrackingGameAttributes',1,'']]],
  ['trackingresults_70',['TrackingResults',['../class_multimorphic_1_1_p3_app_1_1_g_u_i_1_1_tracking_results.html',1,'Multimorphic::P3App::GUI']]],
  ['transition_71',['transition',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_layer.html#a6ae059139cc61941df22f04fb168e4c7',1,'Multimorphic::NetProcGame::dmd::Layer']]],
  ['transition_5fframe_72',['transition_frame',['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_cross_fade_transition.html#ac3681764b45a80443436e4d9703ff61d',1,'Multimorphic.NetProcGame.dmd.CrossFadeTransition.transition_frame()'],['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_expand_transition.html#a4641702fde055814a8cf0ab89d899639',1,'Multimorphic.NetProcGame.dmd.ExpandTransition.transition_frame()'],['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_layer_transition_base.html#a0477c5598c287296bf0f3c3e09215a22',1,'Multimorphic.NetProcGame.dmd.LayerTransitionBase.transition_frame()'],['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_obscured_wipe_transition.html#a16a20becc7e29252a41d53b8de83fb5e',1,'Multimorphic.NetProcGame.dmd.ObscuredWipeTransition.transition_frame()'],['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_push_transition.html#aa5247c6d89e040e6badf9caedabfe14a',1,'Multimorphic.NetProcGame.dmd.PushTransition.transition_frame()'],['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_slide_over_transition.html#a9bf4369a6c9c31160353eb792b1487dd',1,'Multimorphic.NetProcGame.dmd.SlideOverTransition.transition_frame()'],['../class_multimorphic_1_1_net_proc_game_1_1dmd_1_1_wipe_transition.html#af67db1f165a8967053a11acc9e2a2074',1,'Multimorphic.NetProcGame.dmd.WipeTransition.transition_frame()']]],
  ['transmitter_73',['Transmitter',['../class_multimorphic_1_1_p3_1_1_grid_1_1_transmitter.html',1,'Multimorphic::P3::Grid']]],
  ['triggernextplaylistclip_74',['TriggerNextPlaylistClip',['../class_multimorphic_1_1_p3_s_a_1_1_g_u_i_1_1_p3_s_a_audio.html#a9e7e4370b4822267a56026422d8f1640',1,'Multimorphic::P3SA::GUI::P3SAAudio']]],
  ['troughlauncher_75',['TroughLauncher',['../_physical_features.html#TroughLauncherBallEntry',1,'Detecting Balls Shot Into a TroughLauncher'],['../class_multimorphic_1_1_p3_1_1_mechs_1_1_trough_launcher.html',1,'Multimorphic.P3.Mechs.TroughLauncher']]],
  ['troughlauncherconfigfileentry_76',['TroughLauncherConfigFileEntry',['../class_multimorphic_1_1_p3_1_1_config_1_1_trough_launcher_config_file_entry.html',1,'Multimorphic::P3::Config']]],
  ['troughlauncherdefinition_77',['TroughLauncherDefinition',['../struct_multimorphic_1_1_p3_1_1_mechs_1_1_trough_launcher_definition.html',1,'Multimorphic::P3::Mechs']]],
  ['troughlaunchers_78',['TroughLaunchers',['../_physical_features.html#RequestTroughLaunchers',1,'Request Access To TroughLaunchers'],['../_physical_features.html#DetectingShotsViaTroughLaunchers',1,'Shots into TroughLaunchers']]],
  ['troughlaunchers_20section_79',['TroughLaunchers Section',['../_creating_playfield_module.html#ModuleDefinitionTroughLaunchers',1,'']]],
  ['twinklelightshow_80',['TwinkleLightshow',['../class_multimorphic_1_1_p3_s_a_1_1_modes_1_1_twinkle_lightshow.html',1,'Multimorphic::P3SA::Modes']]],
  ['twitchchannelchatters_81',['TwitchChannelChatters',['../class_multimorphic_1_1_p3_app_1_1_twitch_1_1_twitch_channel_chatters.html',1,'Multimorphic::P3App::Twitch']]],
  ['twitchchannelstatus_82',['TwitchChannelStatus',['../class_multimorphic_1_1_p3_app_1_1_twitch_1_1_twitch_channel_status.html',1,'Multimorphic::P3App::Twitch']]],
  ['twitchchatbot_83',['TwitchChatBot',['../class_multimorphic_1_1_p3_app_1_1_twitch_1_1_twitch_chat_bot.html',1,'Multimorphic::P3App::Twitch']]],
  ['twitchmessage_84',['TwitchMessage',['../class_multimorphic_1_1_p3_app_1_1_twitch_1_1_twitch_message.html',1,'Multimorphic::P3App::Twitch']]]
];
