var searchData=
[
  ['machine_0',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['main_20components_20of_20a_20module_20driver_20dll_1',['Main Components of a Module Driver DLL',['../_creating_playfield_module.html#ModuleDriverDLLComponents',1,'']]],
  ['management_2',['Management',['../_game_management.html',1,'Game Management'],['../_customizing_your_game.html#GameManagement',1,'Game Management']]],
  ['manually_20driving_20a_20flipper_3',['Manually Driving a Flipper',['../_physical_features.html#PulsingFlippers',1,'']]],
  ['manually_20driving_20bumpers_4',['Manually Driving Bumpers',['../_physical_features.html#DrivingBumpers',1,'']]],
  ['mapping_20to_20hardware_5',['Mapping To Hardware',['../_creating_app.html#HardwareMapping',1,'']]],
  ['mechanical_20specs_6',['Mechanical Specs',['../_creating_playfield_module.html#PlayfieldModuleMechanicals',1,'']]],
  ['mechanism_7',['A Mode Example: A Kickback Mechanism',['../_physical_features.html#KickbackExample',1,'']]],
  ['mechs_8',['Shots into Mechs',['../_physical_features.html#DetectingShotsIntoMechs',1,'']]],
  ['menu_9',['Feature Menu',['../_additional_platform_features.html#FeatureMenu',1,'']]],
  ['menu_10',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['menu_20configuration_11',['Feature Menu Configuration',['../_persistent_data.html#FeatureMenuGameAttributes',1,'']]],
  ['messages_12',['messages',['../_logging_page.html#CreatingLogs',1,'Creating log messages'],['../_logging_page.html#ViewingLogs',1,'Viewing log messages']]],
  ['methods_13',['LEDScript Helper Methods',['../_physical_features.html#LEDScriptsHelper',1,'']]],
  ['methods_14',['Customizing GameAttribute ToString methods',['../_persistent_data.html#CustomAttributeToString',1,'']]],
  ['mode_15',['Mode',['../_game_management.html#DisablingBackboxColorsMode',1,'Disabling Backbox Colors Mode'],['../_game_management.html#DisablingBonusMode',1,'Disabling Bonus Mode'],['../_game_management.html#DisablingHighScoresMode',1,'Disabling High Scores Mode']]],
  ['mode_20and_20gui_16',['The Layers: Mode and GUI',['../_app_structure.html#ModeGUI',1,'']]],
  ['mode_20events_17',['Sending Mode Events',['../_mode_layer.html#SendingModeEvents',1,'']]],
  ['mode_20events_20in_20gui_20scripts_18',['Receiving Mode Events In GUI Scripts',['../_g_u_i_layer.html#ReceivingModeEventsInGUI',1,'']]],
  ['mode_20example_3a_20a_20kickback_20mechanism_19',['A Mode Example: A Kickback Mechanism',['../_physical_features.html#KickbackExample',1,'']]],
  ['mode_20for_20all_20applications_20',['Base Mode for all Applications',['../_game_management.html#BaseAppMode',1,'']]],
  ['mode_20for_20all_20games_21',['Base Mode for all Games',['../_game_management.html#BaseGameMode',1,'']]],
  ['mode_20layer_22',['Mode Layer',['../_mode_layer.html#EventsInModeLayer',1,'Events in Mode Layer'],['../_mode_layer.html',1,'The Mode Layer']]],
  ['mode_20programming_23',['Introduction to Mode Programming',['../_mode_layer.html#ModeIntr',1,'']]],
  ['modes_24',['Modes',['../_mode_layer.html#ModeOverview',1,'An Overview of P3 Modes'],['../_app_structure.html#Modes',1,'Modes'],['../_g_u_i_layer.html#SendingGUIEventsToModes',1,'Sending Events To Modes'],['../_mode_layer.html#Sub-classing',1,'Sub-classing From Existing Modes']]],
  ['modes_20included_20in_20the_20framework_25',['Modes Included In The Framework',['../_mode_layer.html#IncludedModes',1,'']]],
  ['modetogui_20events_26',['List of ModeToGUI Events',['../_event_list.html#ModeToGUIEventList',1,'']]],
  ['modetomode_20events_27',['List of ModeToMode Events',['../_event_list.html#ModeToModeEventList',1,'']]],
  ['module_28',['Creating Your Playfield Module',['../_creating_playfield_module.html',1,'']]],
  ['module_20definition_20file_29',['Module Definition File',['../_creating_playfield_module.html#PlayfieldModuleDefinitionFile',1,'']]],
  ['module_20definition_20files_30',['Example Module Definition Files',['../_creating_playfield_module.html#ModuleDefinitionExample',1,'']]],
  ['module_20driver_31',['Playfield Module Driver',['../_creating_playfield_module.html#PlayfieldModuleDriver',1,'']]],
  ['module_20driver_20diagnostics_32',['Module Driver Diagnostics',['../_creating_playfield_module.html#ModuleDriverDiagnostics',1,'']]],
  ['module_20driver_20dll_33',['Main Components of a Module Driver DLL',['../_creating_playfield_module.html#ModuleDriverDLLComponents',1,'']]],
  ['module_20driver_20package_34',['Building the Module Driver Package',['../_creating_playfield_module.html#ModuleDriverPackage',1,'']]],
  ['module_20identifier_35',['Playfield Module Identifier',['../_creating_playfield_module.html#PlayfieldModuleID',1,'']]],
  ['module_20local_20gameattributes_36',['Playfield Module Local GameAttributes',['../_persistent_data.html#PlayfieldModuleLocalGameAttributes',1,'']]],
  ['module_20specific_20gameattributes_37',['Playfield Module-Specific GameAttributes',['../_persistent_data.html#PlayfieldModuleGameAttributes',1,'']]],
  ['module_20usb_20device_38',['Playfield Module USB Device',['../_creating_playfield_module.html#PlayfieldModuleUSBDevice',1,'']]],
  ['moduleid_39',['Obtaining A Unique Playfield ModuleID',['../_deployment.html#ObtainingModuleID',1,'']]],
  ['moving_20virtual_20target_40',['A GUI Example: A Moving Virtual Target',['../_g_u_i_layer.html#UIMovingTargetExample',1,'']]],
  ['multimorphic_20p3app_20balllauncher_41',['Initializing The Multimorphic.P3App.BallLauncher',['../_physical_features.html#InitializeBallLauncher',1,'']]],
  ['my_20app_42',['my app',['../_f_a_q.html#Unity5',1,'Can I use Unity version x.y.z to develop my app?'],['../_f_a_q.html#StartingAGame',1,'How do I start a game after running my app?']]],
  ['my_20app_20so_20i_20can_20run_20it_20on_20my_20development_20machine_43',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['my_20development_20machine_44',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['my_20game_20so_20that_20it_20appears_20in_20the_20settings_20menu_45',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]]
];
