var searchData=
[
  ['game_0',['Game',['../_physical_features.html#ChangingFlipperStrength',1,'Changing Flipper Strength During A Game'],['../_customizing_your_game.html',1,'Customizing Your Game'],['../_physical_features.html#ResetFlipperStrength',1,'Resetting Flipper Strength During A Game']]],
  ['game_1',['What&apos;s a game?',['../_overview.html#WhatsAGame',1,'']]],
  ['game_20after_20running_20my_20app_2',['How do I start a game after running my app?',['../_f_a_q.html#StartingAGame',1,'']]],
  ['game_20content_3',['Adding Game Content',['../_adding_game_content.html',1,'']]],
  ['game_20features_4',['Basic Game Features',['../_customizing_your_game.html#BasicGameFeatures',1,'']]],
  ['game_20handling_5',['General Game Handling',['../_persistent_data.html#GeneralGameHandlingGameAttributes',1,'']]],
  ['game_20management_6',['Game Management',['../_game_management.html',1,'Game Management'],['../_customizing_your_game.html#GameManagement',1,'Game Management']]],
  ['game_20section_7',['Game Section',['../_creating_playfield_module.html#ModuleDefinitionGame',1,'']]],
  ['game_20so_20that_20it_20appears_20in_20the_20settings_20menu_8',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['gameattribute_20profiles_9',['Stock GameAttribute Profiles',['../_persistent_data.html#StockProfiles',1,'']]],
  ['gameattribute_20tostring_20methods_10',['Customizing GameAttribute ToString methods',['../_persistent_data.html#CustomAttributeToString',1,'']]],
  ['gameattribute_20values_11',['GameAttribute Values',['../_persistent_data.html#Read_GameAttribute',1,'Reading GameAttribute Values'],['../_persistent_data.html#Write_GameAttribute',1,'Saving GameAttribute Values']]],
  ['gameattributes_12',['GameAttributes',['../_persistent_data.html#AppGameAttributes',1,'App-Specific GameAttributes'],['../_persistent_data.html#BackboxColorAttributes',1,'Backbox Color GameAttributes'],['../_persistent_data.html#UserDefinedGameAttribute',1,'Creating GameAttributes'],['../_persistent_data.html#CustomizingDefaultGameAttributes',1,'Customizing Default GameAttributes'],['../_persistent_data.html#DebugAttributes',1,'Debug GameAttributes'],['../_persistent_data.html#DefaultGameAttributes',1,'Default GameAttributes'],['../_persistent_data.html#GlobalGeneralAudioGameAttributes',1,'Global Audio GameAttributes'],['../_persistent_data.html#GlobalBallTrackingGameAttributes',1,'Global Ball Tracking GameAttributes'],['../_persistent_data.html#GlobalCoilsGameAttributes',1,'Global Coil GameAttributes'],['../_persistent_data.html#GlobalCreditsGameAttributes',1,'Global Credit GameAttributes'],['../_persistent_data.html#GlobalGameAttributes',1,'Global GameAttributes'],['../_persistent_data.html#GlobalGeneralGameplayGameAttributes',1,'Global Gameplay GameAttributes'],['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'Global General Config GameAttributes'],['../_persistent_data.html#GlobalGIGameAttributes',1,'Global General Illumination GameAttributes'],['../_persistent_data.html#GlobalLEDBrightnessGameAttributes',1,'Global LED Brightness GameAttributes'],['../_persistent_data.html#GlobalServoWSGameAttributes',1,'Global Servo Wall/Scoop GameAttributes'],['../_persistent_data.html#PlayfieldModuleLocalGameAttributes',1,'Playfield Module Local GameAttributes'],['../_persistent_data.html#PlayfieldModuleGameAttributes',1,'Playfield Module-Specific GameAttributes'],['../_persistent_data.html#RedemptionAttributes',1,'Redemption GameAttributes'],['../_persistent_data.html#ReplayAttributes',1,'Replay GameAttributes']]],
  ['gameattributes_20from_20gui_20scripts_13',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['gameattributes_20to_20update_20when_20their_20definition_20changes_14',['Forcing GameAttributes to Update when Their Definition Changes',['../_persistent_data.html#GameAttributeCompareOptions',1,'']]],
  ['gameplay_20gameattributes_15',['Global Gameplay GameAttributes',['../_persistent_data.html#GlobalGeneralGameplayGameAttributes',1,'']]],
  ['games_16',['Games',['../_game_management.html#BaseGameMode',1,'Base Mode for all Games'],['../_additional_platform_features.html#TeamGames',1,'Team Games']]],
  ['general_20config_20gameattributes_17',['Global General Config GameAttributes',['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'']]],
  ['general_20game_20handling_18',['General Game Handling',['../_persistent_data.html#GeneralGameHandlingGameAttributes',1,'']]],
  ['general_20illumination_20gameattributes_19',['Global General Illumination GameAttributes',['../_persistent_data.html#GlobalGIGameAttributes',1,'']]],
  ['getting_20started_20',['Getting Started',['../_getting_started.html',1,'']]],
  ['global_20audio_20gameattributes_21',['Global Audio GameAttributes',['../_persistent_data.html#GlobalGeneralAudioGameAttributes',1,'']]],
  ['global_20ball_20tracking_20gameattributes_22',['Global Ball Tracking GameAttributes',['../_persistent_data.html#GlobalBallTrackingGameAttributes',1,'']]],
  ['global_20coil_20gameattributes_23',['Global Coil GameAttributes',['../_persistent_data.html#GlobalCoilsGameAttributes',1,'']]],
  ['global_20credit_20gameattributes_24',['Global Credit GameAttributes',['../_persistent_data.html#GlobalCreditsGameAttributes',1,'']]],
  ['global_20gameattributes_25',['Global GameAttributes',['../_persistent_data.html#GlobalGameAttributes',1,'']]],
  ['global_20gameplay_20gameattributes_26',['Global Gameplay GameAttributes',['../_persistent_data.html#GlobalGeneralGameplayGameAttributes',1,'']]],
  ['global_20general_20config_20gameattributes_27',['Global General Config GameAttributes',['../_persistent_data.html#GlobalGeneralConfigGameAttributes',1,'']]],
  ['global_20general_20illumination_20gameattributes_28',['Global General Illumination GameAttributes',['../_persistent_data.html#GlobalGIGameAttributes',1,'']]],
  ['global_20led_20brightness_20gameattributes_29',['Global LED Brightness GameAttributes',['../_persistent_data.html#GlobalLEDBrightnessGameAttributes',1,'']]],
  ['global_20servo_20wall_20scoop_20gameattributes_30',['Global Servo Wall/Scoop GameAttributes',['../_persistent_data.html#GlobalServoWSGameAttributes',1,'']]],
  ['gui_31',['The Layers: Mode and GUI',['../_app_structure.html#ModeGUI',1,'']]],
  ['gui_20example_3a_20a_20moving_20virtual_20target_32',['A GUI Example: A Moving Virtual Target',['../_g_u_i_layer.html#UIMovingTargetExample',1,'']]],
  ['gui_20layer_33',['GUI Layer',['../_g_u_i_layer.html#EventsInGUILayer',1,'Events in GUI Layer'],['../_g_u_i_layer.html',1,'The GUI Layer']]],
  ['gui_20scripts_34',['Receiving Mode Events In GUI Scripts',['../_g_u_i_layer.html#ReceivingModeEventsInGUI',1,'']]],
  ['gui_20scripts_35',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['guitomode_20events_36',['List of GUIToMode Events',['../_event_list.html#GUIToModeEventList',1,'']]]
];
