var searchData=
[
  ['i_20access_20gameattributes_20from_20gui_20scripts_0',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['i_20add_20a_20new_20setting_20for_20my_20game_20so_20that_20it_20appears_20in_20the_20settings_20menu_1',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['i_20can_20run_20it_20on_20my_20development_20machine_2',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['i_20compile_20my_20app_20so_20i_20can_20run_20it_20on_20my_20development_20machine_3',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['i_20start_20a_20game_20after_20running_20my_20app_4',['How do I start a game after running my app?',['../_f_a_q.html#StartingAGame',1,'']]],
  ['i_20use_20unity_20version_20x_20y_20z_20to_20develop_20my_20app_5',['Can I use Unity version x.y.z to develop my app?',['../_f_a_q.html#Unity5',1,'']]],
  ['identifier_6',['Playfield Module Identifier',['../_creating_playfield_module.html#PlayfieldModuleID',1,'']]],
  ['if_20tilt_20active_7',['Show End-of-Ball Bonus If Tilt Active',['../_game_management.html#ShowBonusEventIfTiltActive',1,'']]],
  ['illumination_20gameattributes_8',['Global General Illumination GameAttributes',['../_persistent_data.html#GlobalGIGameAttributes',1,'']]],
  ['in_20gui_20layer_9',['Events in GUI Layer',['../_g_u_i_layer.html#EventsInGUILayer',1,'']]],
  ['in_20gui_20scripts_10',['Receiving Mode Events In GUI Scripts',['../_g_u_i_layer.html#ReceivingModeEventsInGUI',1,'']]],
  ['in_20mode_20layer_11',['Events in Mode Layer',['../_mode_layer.html#EventsInModeLayer',1,'']]],
  ['in_20the_20framework_12',['Modes Included In The Framework',['../_mode_layer.html#IncludedModes',1,'']]],
  ['in_20the_20settings_20menu_13',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['in_20this_20kit_14',['What&apos;s Included In This Kit',['../_introduction.html#WhatsIncluded',1,'']]],
  ['included_20in_20the_20framework_15',['Modes Included In The Framework',['../_mode_layer.html#IncludedModes',1,'']]],
  ['included_20in_20this_20kit_16',['What&apos;s Included In This Kit',['../_introduction.html#WhatsIncluded',1,'']]],
  ['initializing_20the_20multimorphic_20p3app_20balllauncher_17',['Initializing The Multimorphic.P3App.BallLauncher',['../_physical_features.html#InitializeBallLauncher',1,'']]],
  ['initiating_20high_20score_20comparisons_18',['Initiating High Score Comparisons',['../_persistent_data.html#HighScoreComparisons',1,'']]],
  ['installation_19',['Installation',['../_getting_started.html#Installation',1,'Installation'],['../_getting_started.html#UnityInstallation',1,'Unity Installation']]],
  ['into_20a_20troughlauncher_20',['Detecting Balls Shot Into a TroughLauncher',['../_physical_features.html#TroughLauncherBallEntry',1,'']]],
  ['into_20mechs_21',['Shots into Mechs',['../_physical_features.html#DetectingShotsIntoMechs',1,'']]],
  ['into_20play_22',['Launching Balls Into Play',['../_physical_features.html#TroughLaunching',1,'']]],
  ['into_20scoops_23',['Detecting Balls Shot Into Scoops',['../_physical_features.html#DetectingBallsInScoops',1,'']]],
  ['into_20troughlaunchers_24',['Shots into TroughLaunchers',['../_physical_features.html#DetectingShotsViaTroughLaunchers',1,'']]],
  ['introduction_25',['Introduction',['../_creating_playfield_module.html#CreatingPlayfieldModuleIntroduction',1,'']]],
  ['introduction_20to_20mode_20programming_26',['Introduction to Mode Programming',['../_mode_layer.html#ModeIntr',1,'']]],
  ['introduction_20to_20the_20p3_20sdk_27',['Introduction to the P3 SDK',['../_introduction.html',1,'']]],
  ['is_20there_20an_20easy_20way_20to_20see_20the_20frame_20rate_28',['Is there an easy way to see the frame rate?',['../_f_a_q.html#FrameRate',1,'']]],
  ['it_20appears_20in_20the_20settings_20menu_29',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['it_20on_20my_20development_20machine_30',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]]
];
