var searchData=
[
  ['s_20a_20game_0',['What&apos;s a game?',['../_overview.html#WhatsAGame',1,'']]],
  ['s_20included_20in_20this_20kit_1',['What&apos;s Included In This Kit',['../_introduction.html#WhatsIncluded',1,'']]],
  ['sample_2',['The P3 Application Sample',['../_getting_started.html#SampleApp',1,'']]],
  ['save_20restore_20state_3',['Save/Restore State',['../_additional_platform_features.html#SaveRestore',1,'']]],
  ['saving_20gameattribute_20values_4',['Saving GameAttribute Values',['../_persistent_data.html#Write_GameAttribute',1,'']]],
  ['saving_20operator_20settings_5',['Run Code When Saving Operator Settings',['../_persistent_data.html#RunCodeUponSavingGameAttribute',1,'']]],
  ['saving_20player_20data_6',['Saving Player Data',['../_player_data.html#SavingPlayerData',1,'']]],
  ['scene_7',['Scene',['../_adding_game_content.html#AddScene',1,'Adding a Scene'],['../_g_u_i_layer.html#AnatomyOfScene',1,'Anatomy of a Scene']]],
  ['scene_20controller_8',['Scene Controller',['../_g_u_i_layer.html#SceneController',1,'']]],
  ['scenes_20of_20an_20app_9',['Scenes of an App',['../_g_u_i_layer.html#Scenes',1,'']]],
  ['scoop_20assembly_10',['Wall/Scoop Assembly',['../_physical_features.html#WallScoopAssembly',1,'']]],
  ['scoop_20gameattributes_11',['Global Servo Wall/Scoop GameAttributes',['../_persistent_data.html#GlobalServoWSGameAttributes',1,'']]],
  ['scoops_12',['Scoops',['../_physical_features.html#DetectingBallsInScoops',1,'Detecting Balls Shot Into Scoops'],['../_physical_features.html#RaisingAndLoweringScoops',1,'Raising and Lowering Scoops'],['../_physical_features.html#Scoops',1,'Scoops']]],
  ['score_20categories_13',['High Score Categories',['../_persistent_data.html#HighScoreCategories',1,'']]],
  ['score_20comparisons_14',['Initiating High Score Comparisons',['../_persistent_data.html#HighScoreComparisons',1,'']]],
  ['score_20tables_15',['Displaying High Score Tables',['../_persistent_data.html#DisplayingHighScores',1,'']]],
  ['score_20tracking_16',['High Score Tracking',['../_customizing_your_game.html#HighScoreCheck',1,'']]],
  ['scores_17',['Scores',['../_persistent_data.html#HighScores',1,'High Scores'],['../_adding_game_content.html#PopupScores',1,'Popup Scores']]],
  ['scores_20mode_18',['Disabling High Scores Mode',['../_game_management.html#DisablingHighScoresMode',1,'']]],
  ['scoring_19',['Scoring',['../_customizing_your_game.html#Scoring',1,'']]],
  ['scripts_20',['Receiving Mode Events In GUI Scripts',['../_g_u_i_layer.html#ReceivingModeEventsInGUI',1,'']]],
  ['scripts_21',['How can I access GameAttributes from GUI scripts?',['../_f_a_q.html#FAQSendAttributeToGUI',1,'']]],
  ['sdk_22',['Introduction to the P3 SDK',['../_introduction.html',1,'']]],
  ['search_20configuration_23',['Ball Search Configuration',['../_persistent_data.html#BallSearchGameAttributes',1,'']]],
  ['section_24',['Section',['../_creating_playfield_module.html#BallPaths',1,'BallPaths Section'],['../_creating_playfield_module.html#ModuleDefinitionBumpers',1,'Bumpers Section'],['../_creating_playfield_module.html#ModuleDefinitionCoils',1,'Coils Section'],['../_creating_playfield_module.html#ModuleDefinitionFlippers',1,'Flippers Section'],['../_creating_playfield_module.html#ModuleDefinitionGame',1,'Game Section'],['../_creating_playfield_module.html#ModuleDefinitionLEDs',1,'LEDs Section'],['../_creating_playfield_module.html#ModuleDefinitionLEDStrings',1,'LEDStrings Section'],['../_creating_playfield_module.html#ModuleDefinitionServos',1,'Servos Section'],['../_creating_playfield_module.html#ModuleDefinitionSteppers',1,'Steppers Section'],['../_creating_playfield_module.html#ModuleDefinitionSwitches',1,'Switches Section'],['../_creating_playfield_module.html#ModuleDefinitionTroughLaunchers',1,'TroughLaunchers Section'],['../_creating_playfield_module.html#ModuleDefinitionUpperDisplay',1,'UpperDisplay Section']]],
  ['see_20the_20frame_20rate_25',['Is there an easy way to see the frame rate?',['../_f_a_q.html#FrameRate',1,'']]],
  ['sending_20events_20to_20modes_26',['Sending Events To Modes',['../_g_u_i_layer.html#SendingGUIEventsToModes',1,'']]],
  ['sending_20mode_20events_27',['Sending Mode Events',['../_mode_layer.html#SendingModeEvents',1,'']]],
  ['servo_20wall_20scoop_20gameattributes_28',['Global Servo Wall/Scoop GameAttributes',['../_persistent_data.html#GlobalServoWSGameAttributes',1,'']]],
  ['servos_20section_29',['Servos Section',['../_creating_playfield_module.html#ModuleDefinitionServos',1,'']]],
  ['setting_20default_20flipper_20strength_30',['Setting Default Flipper Strength',['../_physical_features.html#SettingDefaultFlipperStrength',1,'']]],
  ['setting_20for_20my_20game_20so_20that_20it_20appears_20in_20the_20settings_20menu_31',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['settings_32',['Settings',['../_additional_platform_features.html#PlayerProfileSettings',1,'Player-specific Settings'],['../_persistent_data.html#RunCodeUponSavingGameAttribute',1,'Run Code When Saving Operator Settings']]],
  ['settings_20menu_33',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['shot_20into_20a_20troughlauncher_34',['Detecting Balls Shot Into a TroughLauncher',['../_physical_features.html#TroughLauncherBallEntry',1,'']]],
  ['shot_20into_20scoops_35',['Detecting Balls Shot Into Scoops',['../_physical_features.html#DetectingBallsInScoops',1,'']]],
  ['shots_36',['Detecting Playfield Shots',['../_physical_features.html#DetectingShots',1,'']]],
  ['shots_20into_20mechs_37',['Shots into Mechs',['../_physical_features.html#DetectingShotsIntoMechs',1,'']]],
  ['shots_20into_20troughlaunchers_38',['Shots into TroughLaunchers',['../_physical_features.html#DetectingShotsViaTroughLaunchers',1,'']]],
  ['show_20end_20of_20ball_20bonus_20if_20tilt_20active_39',['Show End-of-Ball Bonus If Tilt Active',['../_game_management.html#ShowBonusEventIfTiltActive',1,'']]],
  ['simulating_20leds_40',['Simulating LEDs',['../_physical_features.html#LEDSimulations',1,'']]],
  ['simulator_41',['The Simulator',['../_getting_started.html#Simulator',1,'']]],
  ['slingshot_20configuration_42',['Slingshot Configuration',['../_persistent_data.html#SlingShotGameAttributes',1,'']]],
  ['so_20i_20can_20run_20it_20on_20my_20development_20machine_43',['How do I compile my App so I can run it on my development machine?',['../_f_a_q.html#Compiling',1,'']]],
  ['so_20that_20it_20appears_20in_20the_20settings_20menu_44',['How can I add a new setting for my game so that it appears in the Settings menu?',['../_f_a_q.html#FAQNewAttribute',1,'']]],
  ['soft_20restarts_45',['Soft Restarts',['../_additional_platform_features.html#SoftRestarts',1,'']]],
  ['specific_20gameattributes_46',['Specific GameAttributes',['../_persistent_data.html#AppGameAttributes',1,'App-Specific GameAttributes'],['../_persistent_data.html#PlayfieldModuleGameAttributes',1,'Playfield Module-Specific GameAttributes']]],
  ['specific_20settings_47',['Player-specific Settings',['../_additional_platform_features.html#PlayerProfileSettings',1,'']]],
  ['specs_48',['Specs',['../_creating_playfield_module.html#PlayfieldModuleElectronics',1,'Electronic Specs'],['../_creating_playfield_module.html#PlayfieldModuleMechanicals',1,'Mechanical Specs']]],
  ['stack_49',['The Technology Stack',['../_overview.html#TechnologyStack',1,'']]],
  ['start_20a_20game_20after_20running_20my_20app_50',['How do I start a game after running my app?',['../_f_a_q.html#StartingAGame',1,'']]],
  ['started_51',['Getting Started',['../_getting_started.html',1,'']]],
  ['startup_52',['Keeping Power Relay Off At Startup',['../_game_management.html#KeepingPowerRelayOffAtStartup',1,'']]],
  ['state_53',['Save/Restore State',['../_additional_platform_features.html#SaveRestore',1,'']]],
  ['steppers_20section_54',['Steppers Section',['../_creating_playfield_module.html#ModuleDefinitionSteppers',1,'']]],
  ['stock_20gameattribute_20profiles_55',['Stock GameAttribute Profiles',['../_persistent_data.html#StockProfiles',1,'']]],
  ['strength_56',['Setting Default Flipper Strength',['../_physical_features.html#SettingDefaultFlipperStrength',1,'']]],
  ['strength_20during_20a_20game_57',['Strength During A Game',['../_physical_features.html#ChangingFlipperStrength',1,'Changing Flipper Strength During A Game'],['../_physical_features.html#ResetFlipperStrength',1,'Resetting Flipper Strength During A Game']]],
  ['structure_58',['Structure',['../_deployment.html#DirectoryStructure',1,'Directory Structure'],['../_folders_namespaces.html#AssetsFolder',1,'The Assets Folder Structure'],['../_folders_namespaces.html#NamespaceStructure',1,'The Namespace Structure']]],
  ['structure_20of_20a_20p3_20app_59',['Structure of a P3 App',['../_app_structure.html',1,'']]],
  ['sub_20classing_20from_20existing_20modes_60',['Sub-classing From Existing Modes',['../_mode_layer.html#Sub-classing',1,'']]],
  ['switches_20section_61',['Switches Section',['../_creating_playfield_module.html#ModuleDefinitionSwitches',1,'']]],
  ['synchronizing_20ledscripts_62',['Synchronizing LEDScripts',['../_physical_features.html#SynchronizingLEDScripts',1,'']]],
  ['system_63',['Coordinate System',['../_creating_playfield_module.html#ModuleDefinitionCoords',1,'']]]
];
